### ISSUE TITLE
Project used echo framework generated with standard http package

### ISSUE THREAD

**Issue by dr-dobermann** [Melkeydev/go-blueprint#101]
Generated code uses net/http package instead of echo
`
package server

import (
	"fmt"
	"net/http"
	"time"
)

var port = 8080

type Server struct {
	port int
}

func NewServer() *http.Server {

	NewServer := &Server{
		port: port,
	}

	// Declare Server config
	server := &http.Server{
		Addr:         fmt.Sprintf(":%d", NewServer.port),
		Handler:      NewServer.RegisterRoutes(),
		IdleTimeout:  time.Minute,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
	}

	return server
}`

**Comment by 20pa5a1210** [comment]
No Its same for every project its just server config
