### ISSUE TITLE
Issue templates does not work correctly 

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#105]
Right now if someone creates a new issue there is no template for it even though we have a file in the .github

**Comment by SputNikPlop** [comment]
Ok when I make a new issue it goes to https://github.com/twitchdev/twitch-cli/issues/new/choose then somehow redirects me to https://github.com/twitchdev/twitch-cli/issues/new so this looks like a GitHub issue not a yaml issue

**Comment by EmilMalmsten** [comment]
I made it work by cloning the repo and capitalizing the folder name from `issue_template` to `ISSUE_TEMPLATE` as it is according to this: https://github.com/golang/tools/blob/master/gopls/doc/workspace.md

I guess it's case sensitive?

Cloned repo: https://github.com/EmilMalmsten/test_bp

**Comment by SputNikPlop** [comment]
@EmilMalmsten awesome, thanks for taking care of this for me
