### ISSUE TITLE
Add opt-in DB connection structure 

### ISSUE THREAD

**Issue by xsadia** [Melkeydev/go-blueprint#11]
Setting up a database and connecting to it in Go projects is a trivial task most of the time, but, similar to creating an HTTP server, it becomes repetitive. My proposal is to introduce an opt-in database setup.

**Comment by Melkeydev** [comment]
This is a super nice feature we should include

**Comment by MohammadAlhallaq** [comment]
Are any of you guys working on this, or should I give it a try?

**Comment by Melkeydev** [comment]
> Are any of you guys working on this, or should I give it a try?

It's all you bro!

**Comment by itschip** [comment]
Suggestions for modules:
[GORM](https://gorm.io/)
[Bun](https://bun.uptrace.dev/)

And ofc the std sql, and sqlite

**Comment by silaselisha** [comment]
what about providing an option to pick the type of DB either NoSQL or a relational database as mentioned, std SQL.
