### ISSUE TITLE
Add Completion Scripts

### ISSUE THREAD

**Issue by newtoallofthis123** [Melkeydev/go-blueprint#110]
A suggestion to the cli itself, wouldn't be cool if there were completion scripts for the program for bash, zsh and fish? I mean the program only has like 5 commands, but still :)

**Comment by cedrata** [comment]
It is actually a great idea, I like that, let me try!

**Comment by MitchellBerend** [comment]
Cobra comes with the ability to generate this out of the box. You can run `go-blueprint completion <your shell>` to have it print the script to stdout. You can add that command to your dotfiles directly to always have it up to date or use the completion mechanism of your shell. I don't know how this works on fish, zsh or powershell but bash has `bash-completion`.

The only thing that does not get generated is options for the flags 😞

**Comment by newtoallofthis123** [comment]
I have been trying as well and it is quite weird to do
