### ISSUE TITLE
launching air through makefile not working

### ISSUE THREAD

**Issue by jkellogg01** [Melkeydev/go-blueprint#111]
## Abstract

When using the `make watch` command I get the response `air is not installed. Do you want to install it now? (y/n)` Even though air is installed and is in my `$GOPATH/bin`.

## Issue Replication

Machine type: darwin amd64 (206 macbook pro)

## Expected Behavior

With my environment laid out as it is this command should run air the way it does when I use the `air` command

**Comment by narasaka** [comment]
do you have `$GOPATH` configured? what's the output when you type `echo $GOPATH` in your terminal?
