### ISSUE TITLE
[Feature Request] Using pgx instead of pq

### ISSUE THREAD

**Issue by anthonyg876** [Melkeydev/go-blueprint#126]
### Tell us about your feature request

Looking at the README, it says that pq and mattn/sqlite3 are the supported database drivers, but I do not find these to be the best options for these databases.

**For postgres**:

-  They literally say that they are only in maintenance mode, probably heading into the same route that gorilla was in a few months ago. I think a better choice would be to switch it to have users integrate and use pgx instead!

**For sqlite**

-  Using mattn's driver is a great choice, but the driver ships with cgo, which can present scary errors that can be difficult to solve. I feel that using modernc.or/sqlite would be best, since they do not use cgo for the library, and only use it for testing the library.

### Disclaimer

- [X] I agree

**Comment by Melkeydev** [comment]
@anthonyg876 I believe we just recently changed to pgx.
 As for SQLite, that is pretty cool, not a bad idea. Do you mind closing this issue and opening a new one specific for SQLite driver?

**Comment by anthonyg876** [comment]
@Melkeydev Yeah, that works out, when I read the README, it mentioned that it used pq.
