### ISSUE TITLE
[Bug] Remove Homebrew Installation

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#130]
### What is the problem?

Homebrew keeps breaking and we can just delete it 

### Operating System

bruh

### Architecture Version (x86, x64, arm, etc)

etc 

### Steps to reproduce

look at GHA and all the broken homebrew builds

### Relevant log output

```shell
Melkey does not like this
```

**Comment by hackastak** [comment]
I'll take this one @Melkeydev

**Comment by Melkeydev** [comment]
I think to get started with programming @beginbot you should check these types of issues out first, before making a substantial PR!
All the best in your future skills, and if you want to contribute further we will be happy to check it out :)

**Comment by Melkeydev** [comment]
@hackastak its yours
