### ISSUE TITLE
Looking for a Core Maintainer

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#132]
### Tell us about your feature request

As blueprint gets bigger, I would really enjoy if someone volunteers to become an active core maintainer.
Preferably someone who has been already contributing as well.
Please comment here or ping me on Discord if you are interested!

### Disclaimer

- [X] I agree

**Comment by anthonyg876** [comment]
Hey Melkey, I am not a current contributor at the moment, but I would love to become a core maintainer of this project.

I am currently a junior Software Engineer who has been working with Go for the past 6 months. I could see this as a huge opportunity!

**Comment by SputNikPlop** [comment]
I am happy to do some docs maybe though thats probably a side thing as the project grows bigger.

**Comment by limesten** [comment]
Interested! I'd love to help make this project the best it can be 🚀
I'll try to catch u on discord when I see u online

**Comment by hacked0ne** [comment]
I am interested! I have python knowledge, and now learning Golang. I would love to make some impact to the project.

**Comment by Ujstor** [comment]
@Melkeydev I am ready for this duty
