### ISSUE TITLE
[Bug] Update the README

### ISSUE THREAD

**Issue by anthonyg876** [Melkeydev/go-blueprint#133]
### What is the problem?

When I first used the tool, I found that the README referenced pq instead of the current postgres driver it installs when you select postgres, which is pgx. This is a minor change that led me to believe that the driver installed would be pq.

### Operating System

all

### Architecture Version (x86, x64, arm, etc)

x86

### Steps to reproduce

Look at the README and click the postgres link.

**Comment by Ujstor** [comment]
You referring to the issue with the incorrect link in the README file for the PSQL driver:

<img width="282" alt="Code_1bhR5pVmUb" src="https://github.com/Melkeydev/go-blueprint/assets/116409846/9096b813-3f1e-401a-b897-68f2d37aff2a">

<img width="328" alt="Code_v0QzaWlo4U" src="https://github.com/Melkeydev/go-blueprint/assets/116409846/28915f98-eb51-4908-b7a5-c0f0c5b9b4af">

This is correct link for README.md update

https://github.com/jackc/pgx/
