### ISSUE TITLE
[Bug] Spinner not working

### ISSUE THREAD

**Issue by SudoSurya** [Melkeydev/go-blueprint#144]
### What is the problem?

spinner is not working if we use flags. its only working if we use cmd `go-blueprint create` directly 

### Operating System

Linux 

### Architecture Version (x86, x64, arm, etc)

x86

### Steps to reproduce

![image](https://github.com/Melkeydev/go-blueprint/assets/95855318/66d8824e-ccc2-467b-9f0c-3f0f51bae453)

**Comment by Melkeydev** [comment]
Oh thats interesting...
I can take a look at this right now
