### ISSUE TITLE
[Feature Request] --advanced flag for additional step options

### ISSUE THREAD

**Issue by Ujstor** [Melkeydev/go-blueprint#147]
Running 'go-blueprint create --advanced' would provide more options, but simply running 'go-blueprint create' would maintain the current steps: frameworks and database drivers. In this step, it would be nice if users had the option for multiple choices.

In the [staging-2 branch](https://github.com/Melkeydev/go-blueprint/tree/staging-2), PR #108, which includes GitHub Action Templates for generated projects, has been merged. You can test this feature on this branch by implementing it with this PR.

There is also interest in HTMX/Templ support in issue #125, and for future-added features, multi-choice implementation is a great option to consider.

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
@briancbarrow This is yours if you want it; you already worked on this in PR #139

**Comment by briancbarrow** [comment]
@Ujstor sounds good! I am hoping to have this ready soon. If the flag is not provided do we want to prompt the user if they want to add advanced features? Or have it go through the options only if the provide the flag?

**Comment by Ujstor** [comment]
You got it right, only if the flag is provided, a step like this one in the example is available. I believe this fourth prompt can be utilized for other features, such as a multi-choice option, although I'm not sure how to implement it. 

It would be great to implement a non-interactive command, but that should be done step by step. If others are interested, they can contribute to the process. This is a substantial amount of work for one person. Please let me know how I can help

<img width="463" alt="wstep" src="https://github.com/Melkeydev/go-blueprint/assets/116409846/5342aef8-e23f-4577-9f52-6a96554bda58">

**Comment by Ujstor** [comment]
GG
