### ISSUE TITLE
[Feature Request]: Wiki for new Go Developers

### ISSUE THREAD

**Issue by that-ambuj** [Melkeydev/go-blueprint#153]
Hi, I am quite new to Go but I have a decent amount of experience in Rust and Typescript.

The Project structure looks quite good at first but I'm having a few issues when using this tool.

- I can't define routes in a separate module other than `server` because it's not allowed to define methods on foreign types i.e. `FiberServer`.
- I don't quite understand the purpose of `FiberServer` because on one hand it allows sharing the database connection by `db` field across requests rather than using global variables but It is hidden behind the `Service` interface which disallows accessing the private type `service` which has the database connection in itself. 

So, my question is how am I supposed to run queries in a handler when the database connection is hidden behind a private type? And how do I separate my routes to a separate folder other than the server directory?

My idea is that as this project gets more popular, people might have more of such similar question. Building a dedicated wiki to help new users to take directions and hints from would be a great help. It would help them know how to do certain things instead of going into intricacies of Go's type system.

### Disclaimer

- [X] I agree

**Comment by Melkeydev** [comment]
Your specific question is directly related to Fiber framework and how Fiber handles their routes. However, we developed this project so that you can modify the routes however you want.

**Comment by Melkeydev** [comment]
I am also not against a Wiki, I think it's a good idea

**Comment by that-ambuj** [comment]
> Your specific question is directly related to Fiber framework and how Fiber handles their routes. However, we developed this project so that you can modify the routes however you want. 

The database struct `service` is a private type that holds the database pointer. And this happens in every framework that this framework produces. It's not specific to fiber, it's specific to how go-blueprint structures the project.

I have modified the FiberServer struct and directly embedded *sql.DB in it for better access.
