### ISSUE TITLE
[Feature Request] Adding go-fx support for DI pattern with existing frameworks.

### ISSUE THREAD

**Issue by NimishKashyap** [Melkeydev/go-blueprint#161]
### Tell us about your feature request

Dependency Injection and Inversion of Control is a pattern largely adopted by the Spring ecosystem in Java land with huge success. Although it has an initial learning curve writing scalable applications becomes easier and maintainable with this approach. 

Uber has already introduced `GO-FX`, a dependency injection framework for Go that is maintainable yet flexible enough to write any application in Go. I believe adding DI support for `go-blueprint` powered by [gofx](https://github.com/uber-go/fx) would help developers generate the initial boilerplate code that is required to get started with the application framework.

Ps. I think it'll be suitable with the `--advanced` flag.
### Disclaimer

- [X] I agree

**Comment by briancbarrow** [comment]
@NimishKashyap Is this something you want to work on adding?

**Comment by Ujstor** [comment]
I am closing this one because there is no interest from the author for implementation. Also, I think this is a more advanced approach. It doesn't exactly fit into the blueprint.
