### ISSUE TITLE
[Feature Request] Create a WEB UI component that can spin everything up for a user 

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#168]
### Tell us about your feature request

Have a web ui with a domain that users can go to and pick different things they want for their Go project with a live preview feature

![image](https://github.com/Melkeydev/go-blueprint/assets/53410236/4cebcc79-f1a0-4cc2-8812-b0c0bd3d6038)

### Disclaimer

- [X] I agree

**Comment by bsquidwrd** [comment]
This idea is pure fire 🔥

**Comment by xsadia** [comment]
maybe use github API to generate a repo for the user

**Comment by briancbarrow** [comment]
This would be amazing. @bsquidwrd are you going to look into this or should I take a stab at it?

**Comment by bsquidwrd** [comment]
@briancbarrow I have no frontend experience, so I don't even know where to begin on this. Feel free to have at it!

**Comment by briancbarrow** [comment]
@Melkeydev I have a couple of clarifying questions.

- What kinds of things are you thinking would show up in the Preview section? 
- What is the ideal end result here?
    - A URL to the initialized git repo on the user's account?
    - A url to a repo initialized on an account they then clone?
    - A zip of the project they download?

**Comment by briancbarrow** [comment]
@Melkeydev 

Yeah, that makes sense. Were you hoping the git clone link is to a repo on their Github profile?

**Comment by briancbarrow** [comment]
This is done and can be found at https://go-blueprint.dev/
