### ISSUE TITLE
Adding WebSocket

### ISSUE THREAD

**Issue by Bilal-Nizamani** [Melkeydev/go-blueprint#174]
### Tell us about your feature request

I think this blueprint lacks WebSocket options, which many people use. I believe at least the initialization of WebSockets or, if possible, simple functionality for creating rooms, connecting, disconnecting, broadcasting messages, and adding someone to a room would be helpful. Maybe something simpler that makes the code structure clear about what you're trying to achieve. I am new to it, and Melkey your blueprint pkg really improved my understanding of Golang very fast. Thanks!

### Disclaimer

- [X] I agree

**Comment by briancbarrow** [comment]
@Bilal-Nizamani would you be interested in working on this?

**Comment by MitchellBerend** [comment]
I worked on #27 a while back which is also about adding websocket stuff. I'd definitely be willing to help with this if this is something that is considered useful now.

**Comment by briancbarrow** [comment]
@MitchellBerend do you remember why we closed your original PR?

**Comment by MitchellBerend** [comment]
It was considered outside the scope of this project iirc. The user experience was also not that great but I think that can be different this time around since the `--advanced` flag exists now.

**Comment by briancbarrow** [comment]
@MitchellBerend  now that we have the `--advanced` flag, you are good to tackle it. Want me to assign it to you?

**Comment by MitchellBerend** [comment]
As this is @Bilal-Nizamani's issue he should get first pick, but I will take it if he can't or doesn't want it.

**Comment by Bilal-Nizamani** [comment]
I don't know how this issue system works. Do I have to fix the issue after pointing it out, or is my duty just to report the issue and those who are running the project will fix it? I have never worked on open-source projects before. I did not intend to solve the issue; I was just pointing it out so someone else may solve it.

**Comment by MitchellBerend** [comment]
@Bilal-Nizamani Since you opened the issue I thought maybe you wanted to work on it and I thought it would be polite to ask but I can definitely work on this. I was using my own fork that was way behind since I actually also use websockets a decent amount.

As far as what you **need** to do. Reporting it is already enough in my book since that already helps others.
