### ISSUE TITLE
[Feature Request] Adding support for AWS SDK for services like S3, Secrets Manager etc.

### ISSUE THREAD

**Issue by neymarsabin** [Melkeydev/go-blueprint#180]
### Tell us about your feature request

It would be good if there was an option to initialize AWS SDK, because working with services like S3, secrets manager, parameter store is common with services. I would like to work on it if none's working on it?

### Disclaimer

- [X] I agree

**Comment by briancbarrow** [comment]
@neymarsabin thanks for making the request. What do you envision for this feature? How will it relate to the rest of the project setup?

We're trying to keep this tool unopinionated and be selective about the features we add. The main concern with adding support for AWS services that opens up the floodgates for all the different services out there. 

That being said, we would love to hear what you think how it fits in and we can decide from there.

**Comment by neymarsabin** [comment]
@briancbarrow Hello 👋 Maybe this issue should have been a "Question", rather than "Feature Request". I have been using this project a lot lately, and anything related to AWS always has something like SDK setup, services connecting to secrets manager etc. 
So, the idea behind this issue was to be able to spin up services easily that would include aws sdks as a part of it. I think it would be a good framework to start with/for projects. And, I believe a large part of projects use AWS and already has that as a requirement to start with.
And, yeah I agree, implementation option with aws will bring in PRs down to heroku 😄

**Comment by briancbarrow** [comment]
@neymarsabin we discussed this and have decided that while this would be nice to have, we don't think it is in the scope of this particular project. 

It would be better to have a separate tool for AWS and other cloud services.
