### ISSUE TITLE
[Feature Request] Add support for advanced features to be chosen inside flags

### ISSUE THREAD

**Issue by briancbarrow** [Melkeydev/go-blueprint#183]
### Tell us about your feature request

Currently a user can only select whether or not they want to choose from the advanced features when going through the prompts. There is no way to specify which features to add from the command line flags. Adding this will allow for faster setup if someone already knows what features they want. 

This will also allow for advanced features to be included in the UI from issue #we

### Disclaimer

- [X] I agree

**Comment by Marcellofabrizio** [comment]
@briancbarrow, could it be something like this?

`go-blueprint create --advanced --features htmx go-workflow`

**Comment by briancbarrow** [comment]
> @briancbarrow, could it be something like this?
> 
> `go-blueprint create --advanced --features htmx go-workflow`

Yeah, that's basically what I was thinking

**Comment by Marcellofabrizio** [comment]
Ok, this seems like a good first issue.

**Comment by briancbarrow** [comment]
@Marcellofabrizio do you want me to assign it to you?

**Comment by Marcellofabrizio** [comment]
@briancbarrow Yes, assign it to me. I had a look at the code yesterday. I'm fairly new to Go, but I'll make sure it's a nice solution 🙂

**Comment by briancbarrow** [comment]
@Marcellofabrizio 👍 Let us know if you need anything.

**Comment by Marcellofabrizio** [comment]
@briancbarrow I created a PR for this #184

**Comment by Marcellofabrizio** [comment]
Hey @briancbarrow, I was wondering if there's something wrong in the PR since no one commented on it in a week. Did you manage to have a look?

**Comment by briancbarrow** [comment]
> Hey @briancbarrow, I was wondering if there's something wrong in the PR since no one commented on it in a week. Did you manage to have a look?

I haven't had a chance to look at it yet. Sorry.

**Comment by briancbarrow** [comment]
@Marcellofabrizio I finally had a chance to review it. Left some comments. Feel free to reach out if you have any questions.
