### ISSUE TITLE
[Feature Request] Adding workflow support for templ generation step

### ISSUE THREAD

**Issue by MitchellBerend** [Melkeydev/go-blueprint#185]
### Tell us about your feature request

Right now if you choose the htmx and workflow option in the `--advanced` menu, the workflow that get's generated does not add a `templ generate` step in the workflow files. It's a minor inconvenience but it would be nice if that worked out of the box.

### Disclaimer

- [X] I agree

**Comment by briancbarrow** [comment]
This is a good idea and a good catch @MitchellBerend. We should definitely get this added.

**Comment by Ujstor** [comment]
Resolved in #277
