### ISSUE TITLE
[Feature Request] Adding Tailwind Configuration to the Initial Setup

### ISSUE THREAD

**Issue by Nevoral** [Melkeydev/go-blueprint#186]
### Tell us about your feature request

Right now, we have everything ready for web development, but Tailwind is part of my stack, and I need to configure it manually. So, adding a Tailwind option for the initial setup should be fine.

### Disclaimer

- [X] I agree

**Comment by briancbarrow** [comment]
@Nevoral I agree this would be a great addition. It has been on my radar as well. At some point I plan on adding it, but if you want to tackle adding it to the advanced flag process, let me know and I will assign the issue to you.

**Comment by briancbarrow** [comment]
Awesome. I've assigned the issue to you @Nevoral.
