### ISSUE TITLE
[Feature Request] Rename Redis to Valkey

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Melkeydev/go-blueprint#202]
### Tell us about your feature request

Redis has changed their license, and it might not be `usable/prohibited` for future use, especially for building large RESTful APIs/websites using the template from this repository.

Source [`Valkey`](https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community)

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
Thanks for that. We need to decide what to do with Redis. The new licensing thing is a issue.

**Comment by briancbarrow** [comment]
I _think_ we are okay still beause we are using [go-redis](https://github.com/redis/go-redis) which is still under the BSD-2 license. I could be wrong.

**Comment by H0llyW00dzZ** [comment]
> I _think_ we are okay still beause we are using [go-redis](https://github.com/redis/go-redis) which is still under the BSD-2 license. I could be wrong.

@briancbarrow that only client

**Comment by Ujstor** [comment]
@H0llyW00dzZ 
Didn't they implement the similar license as MongoDB?
I don't know how specific the limitations are for small users, big corp are another story.

https://www.theregister.com/2024/03/22/redis_changes_license/

What we can do is limit the Docker image to version 7.2. As with Mongo, users will still use the services they need

**Comment by H0llyW00dzZ** [comment]
> @H0llyW00dzZ Didn't they implement the similar license as MongoDB? I don't know how specific the limitations are for small users, big corp are another story.
> 
> https://www.theregister.com/2024/03/22/redis_changes_license/
> 
> What we can do is limit the Docker image to version 7.2. As with Mongo, users will still use the services they need If over time, valkey proves to be as good and reliable as Redis, we can change it easily

@Ujstor It's different. Also, regarding the limitation, I don't really know if it's only about the limitation or if it's also about publishing the software as free and open-source.

**Comment by Ujstor** [comment]
How I understand this new licensing thing, the most affected are companies that resell services and software closely integrated with Redis, and it takes effect after the Redis 7.4 release. But what I know, I am not a lawyer. 

That's a reason why I propose fixing the Docker image to version 7.2.4.
