### ISSUE TITLE
[Feature Request] Implement Own CI/CD for Running Golang Linter Instead of Node.js

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Melkeydev/go-blueprint#208]
### Tell us about your feature request

It would be better to implement our own CI/CD for running the Golang linter, as it looks confusing to run it using Node.js instead of Go.

For example, see how confusing running on Node.js this looks:
![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/dcf5cdeb-6a1b-466d-a701-8bbe7696220d)

### Disclaimer

- [X] I agree

**Comment by briancbarrow** [comment]
@H0llyW00dzZ Do you have any suggestions for what we could use?

**Comment by H0llyW00dzZ** [comment]
> @H0llyW00dzZ Do you have any suggestions for what we could use?

@briancbarrow, golangci-lint can be installed independently from https://golangci-lint.run/

I think it's possible to create something similar to their [`CI/CD`](https://github.com/golangci/golangci-lint-action), but running in Golang instead of TypeScript/JavaScript.

**Comment by H0llyW00dzZ** [comment]
because their [`CI/CD`](https://github.com/golangci/golangci-lint-action) use this https://golangci-lint.run/

**Comment by Ujstor** [comment]
I was cooking with @MitchellBerend
