### ISSUE TITLE
[Feature Request] Implement Another NoSQL Database

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Melkeydev/go-blueprint#211]
### Tell us about your feature request

As currently the database only supports 5 databases, I would like to request the implementation of another NoSQL database. I have experience with NoSQL databases like Firestore/Datastore on Google Cloud, and they are quite useful for serverless applications.

## Justification
NoSQL databases offer a flexible schema, horizontal scaling, and better performance for certain use cases compared to traditional relational databases. By adding support for another NoSQL database, the project can cater to a wider range of use cases and provide more options for developers.

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
For now, we are not accepting new databases. The aim is to minimize the number of db-s and avoid bloat. Implementing any database in the blueprint is straightforward, simply as adjusting the connection string, driver, and specific env-s
