### ISSUE TITLE
[Feature Request] Clear Cache for golangci-lint

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Melkeydev/go-blueprint#216]
### Tell us about your feature request

![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/a20c137b-0080-4fcf-879b-2e71c4c5971c)

> [!NOTE] 
> It's better to remove the cache automatically after running the jobs, because we don't really need it as Go is fast, unlike Rust or other compiled languages that have slow compilers.

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
I need to check how to disable cache. Good idea!

**Comment by H0llyW00dzZ** [comment]
> I need to check how to disable cache. Good idea!

@Ujstor I think it must be independently by creating another workflows for removing it

**Comment by Ujstor** [comment]
After taking a quick look at the cache issue, I'm not sure if I want to mess with it. The new CI and linter are good improved.  I think expected benefits are not justifying the struggle.

https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions

**Comment by H0llyW00dzZ** [comment]
> After taking a quick look at the cache issue, I'm not sure if I want to mess with it. The new CI and linter are good improved. I think expected benefits are not justifying the struggle.
> 
> https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions

That's it, I think, for removing the cache.

Because there are so many cache that we don't really needed, when looking at this:
![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/772a7877-6b45-4b76-aed1-d6686e5d280c)

**Comment by Ujstor** [comment]
I thought cache is automatically deleted when it hits a limit... If not, then we need to create a workflow to clean it

**Comment by H0llyW00dzZ** [comment]
> I thought cache is automatically deleted when it hits a limit... If not, then we need to create a workflow to clean it

@Ujstor I don't think so it will automatically deleted, It's better create a workflow to clean it
