### ISSUE TITLE
[Bug] We are unable to create docker-compose.yml file for an SQLite database

### ISSUE THREAD

**Issue by adit1o** [Melkeydev/go-blueprint#229]
### What is the problem?

```
We are unable to create docker-compose.yml file for an SQLite database
2024/04/15 12:47:18 Could not go tidy in new project exit status 1
Error: exit status 1
```

### Operating System

Ubuntu

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

-

### Relevant log output

```shell
-
```

**Comment by H0llyW00dzZ** [comment]
> ### What is the problem?
> ```
> We are unable to create docker-compose.yml file for an SQLite database
> 2024/04/15 12:47:18 Could not go tidy in new project exit status 1
> Error: exit status 1
> ```
> 
> ### Operating System
> Ubuntu
> 
> ### Architecture Version (x86, x64, arm, etc)
> x64
> 
> ### Steps to reproduce
> 
> ### Relevant log output
> ```shell
> -
> ```

`2024/04/15 12:47:18 Could not go tidy in new project exit status 1`
It's module issue - docs [`here`](https://golang-id.org/blog/using-go-modules/)

**Comment by briancbarrow** [comment]
@adit1o what were the options you selected when creating a new project?

**Comment by adit1o** [comment]
Hi, dunno why, but after i upgrade `apt upgrade` everything looks fine.

so i'm close this issue

**Comment by jonleopard** [comment]
I'm getting this same error. Here are my options:

`go-blueprint create --name welcome --framework chi --driver sqlite --advanced --feature htmx --feature tailwind`

I'm on an M3 Mac running the latest Go 1.22.4. Happy to provide more details if needed!
<img width="801" alt="Screenshot 2024-06-14 at 14 53 59" src="https://github.com/Melkeydev/go-blueprint/assets/2111234/e8b5190f-4c3e-47e8-91ab-f92688500175">
