### ISSUE TITLE
[Feature Request] Enhance Subs Args `--driver` (Database) for Multiple Databases

### ISSUE THREAD

**Issue by H0llyW00dzZ** [Melkeydev/go-blueprint#235]
### Tell us about your feature request

Currently, the `--driver` argument for the `subs` command only supports a single database. it would be beneficial to implement support for multiple databases within the `--driver` argument.

### Example:

For instance, the command could be used as follows:

```bash
go-blueprint create --name gopher-project --framework fiber --driver mysql-redis
```

This would allow `gopher` to specify multiple databases separated by commas or hyphen.

### Benefits:

Supporting multiple databases through the `--driver` argument would provide a better `gopher` experience and more flexibility when creating projects with `go-blueprint`. It would enable `gophers` to easily set up projects with different database combinations based on their requirements.

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
@H0llyW00dzZ 
This would be very interesting if you could implement SQL and Redis databases in the cache configuration for advanced flag.

Blueprint core, we will leave it as it is, but additional features can be implemented as AF. 

Now my question is, can this also be testable? An endpoint or any other kind of test that can give feedback to the user?

**Comment by H0llyW00dzZ** [comment]
> @H0llyW00dzZ This would be very interesting if you could implement SQL and Redis databases in the cache configuration for advanced flag.
> 
> Blueprint core, we will leave it as it is, but additional features can be implemented as AF.
> 
> Now my question is, can this also be testable? An endpoint or any other kind of test that can give feedback to the user?

@Ujstor I'm not sure about the testability because even though it's possible to write a test, it might be difficult and challenging due to the need for credentials and setting up a local server just for testing connect into database.

**Comment by H0llyW00dzZ** [comment]
basically not worthy testable for database

**Comment by Ujstor** [comment]
There is a chance that we will implement models and sample data insertion into the database, with Goose migrations. If this is implemented, then there will be a way to showcase and test the cache database configuration

**Comment by Melkeydev** [comment]
We spoke about this - and as of right now we dont think we want to include a niche feature like this in blueprint!
