### ISSUE TITLE
[Bug] git config not detected when it contains includeif

### ISSUE THREAD

**Issue by paluszkiewiczB** [Melkeydev/go-blueprint#238]
### What is the problem?

After selecting the router and database I see an error:

```
user.email is not set in git config.
Please set up git config before trying again.
The program encountered an unexpected issue and had to exit. The error was: 
GIT CONFIG ISSUE: user.email is not set in git config.

If you continue to experience this issue, please post a message on our GitHub page or join our Discord server for support.
```

I'm not using global git config to avoid mixing 'private' commits with 'enterprise' ones.

My `~/.gitconfig` is a  bunch of `includeIf` sections which choose correct `.gitconfig` based on a current working directory.
```
$ cat ~/.gitconfig
[includeIf "gitdir:~/github/"]
  path = .gitconfig_github
[includeIf "gitdir:~/personal/"]
  path = .gitconfig_gitlab
[includeIf "gitdir:~/proj1/"]
  path = .gitconfig_customer1
[includeIf "gitdir:~/proj2/"]
  path = .gitconfig_customer1
[includeIf "gitdir:~/proj3/"]
  path = .gitconfig_customer2
[core]
	autocrlf = input
```

Then my 'user' section is filled per-customer (different e-mail addresses or casing for the name).

I'm not familiar with the project, just saw the video: https://www.youtube.com/watch?v=1ZbQS6pOlSQ and though you might want to consider more complex git configs.

Actually I do not understand why on earth this tool tries to **commit under my name**?

Readme says: 
> Go Blueprint is a CLI tool that allows users to spin up a Go project with the corresponding structure seamlessly. It also gives the option to integrate with one of the more popular Go frameworks (and the list is growing with new features)!

Not a single word about git or creating commits :no_mouth: 

### Operating System

Ubuntu 20.04

### Architecture Version (x86, x64, arm, etc)

x86

### Steps to reproduce

1. Start with your `.gitconfig` working as expected.
2. Rename it to `.includeme`
3. Create empty `.gitconfig`, which includes your original config 
```
[includeif "gitdir:~/tmp/"]
    path = .includeme
```
4. `cd /tmp`
5. `go run github.com/melkeydev/go-blueprint@latest create`
6. choose whatever
7. it will fail

### Relevant log output

```shell
user.email is not set in git config.
Please set up git config before trying again.
The program encountered an unexpected issue and had to exit. The error was: 
GIT CONFIG ISSUE: user.email is not set in git config.

If you continue to experience this issue, please post a message on our GitHub page or join our Discord server for support.
```

**Comment by Ujstor** [comment]
Early on in the project, a decision was made that the initial commit would be executed upon project creation. The project is still in its early stages, and we didn't take 'advanced' git configuration into consideration. We can open a ticket to address these posible changes if someone wants to implement it.

For now it needs global user and email in .gitconfig

[user]
    email = globalemail@email.com
    name = Global Name

```bash
git config --global user.name "Your Name"
git config --global user.email "youremail@yourdomain.com"
```

**Comment by paluszkiewiczB** [comment]
Thank you for the explanations.

Feel free to close this issue.
