### ISSUE TITLE
[Bug] Microsoft Windows build with Makefile not works

### ISSUE THREAD

**Issue by gustavonobreza** [Melkeydev/go-blueprint#240]
### What is the problem?

When executing the `make` command in the terminal, it generates the file "file_name" (without extension).
When executed in the terminal `.\name_of_file` without the command returns but nothing is executed, because the ".exe" extension is missing.

The solution is detect the OS, if it was Windows then add ".exe" extension in the builded file.  

### Operating System

Microsoft Windows 11

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

1 - Using Windows generate a `go-blueprint` project with any configuration
2 - Install GNU/Make for Windows [using Scoop installer](https://scoop.sh/#/apps?q=make) [GNU Make homepage](https://www.gnu.org/software/make/)
3 - Run `make` or `make build`
4 - This will generate the `main` file, without extention.
5 - When `.\main` is executed the program returns but the app is not excuted.
6 - To fix this just is need rename file `.\main` to `.\main.exe`
7 - Later then run `.\main.exe` and everything works as expected

**Comment by Ujstor** [comment]
Build a command inside the Makefile  includes the argument -o main, which instructs it to output a binary with a specific name:

```makefile
build:
	@echo "Building..."
	@go build -o main cmd/api/main.go
```

You can remove that to get the default .exe, or manually run go build cmd/api/main.go.

However, you can run the main binary that you get from the original Makefile configuration in your PowerShell with:

```cmd
 start main
```

**Comment by Ujstor** [comment]
I am closing this as resolved
