### ISSUE TITLE
[Feature Request] Allow to optionally create git repository

### ISSUE THREAD

**Issue by tomasohCHOM** [Melkeydev/go-blueprint#249]
### Tell us about your feature request

Hello! First and foremost, I love this tool for creating new well-structured Go projects as someone who just started picking the language. My minor feature request: when creating a new project, go-blueprint automatically initializes a git repository and commits all the initial files. It would be nice if the user was given some more options with how the git repo is initialized:

1. Initialize the git repository and commit the changes
2. Initialize the git repository but ONLY stage the changes
3. Proceed without initializing a git repository

This approach is similar to how Create T3 App handles it (except it does not have an option to automatically commit, just staging): [Create T3 App](https://github.com/t3-oss/create-t3-app).

I was not sure if this would be considered a breaking change, please let me know if it is.

### Disclaimer

- [x] I agree

**Comment by Melkeydev** [comment]
Great suggestion - we discussed and will be implementing this a feature in a future release!

**Comment by briancbarrow** [comment]
@tomasohCHOM definitely! I'll assign the issue to you and you can start working on it.

**Comment by tomasohCHOM** [comment]
For sure, I will start working on it right now. Thank you!

**Comment by Ujstor** [comment]
Implemented in #270
