### ISSUE TITLE
Websocket example implementation

### ISSUE THREAD

**Issue by MitchellBerend** [Melkeydev/go-blueprint#25]
Would a ping pong web socket endpoint example add a lot of value? The way I imagine it, it would add a [dependency](https://pkg.go.dev/nhooyr.io/websocket) to the generated project, this dependency does get linked to by the [docs](https://pkg.go.dev/golang.org/x/net/websocket).

I think gorilla has their own websocket implementation but I haven't worked with that one yet.

naive example implementation
```go

handler(w http.ResponseWriter, req *http.Request) {
	socket, _ := websocket.Accept(w, req, nil)
	ctx := req.Context()
	for {
		_, socketBytes, _ := socket.Read(ctx)
		if string(socketBytes) == "PING" {
			_ = socket.Write(ctx, websocket.MessageText, "PONG")
		} else {
			_ = socket.Write(ctx, websocket.MessageText, "HUH?")
		}
	}
}


```

**Comment by Melkeydev** [comment]
:thinking: I am not against it - but I am thinking what would be the value add in terms of what go-blueprint attempts to provide, which is an easy way for users to get started with a Go project. 
If we a websocket, how will that work with the other frameworks?

**Comment by MitchellBerend** [comment]
I would try and reuse the same handler if possible for all frameworks but I would have to look at each framework to see if that is possible.

**Comment by MitchellBerend** [comment]
Okay so I picked gin as my first target and it is possible to keep the same handler function but gin's way of passing the `ResponseWriter` and `Request` are a little different than the standard lib. I will open a pr for this so this issue does not get clogged with implementations.

![image](https://github.com/Melkeydev/go-blueprint/assets/45570310/3dbc36c4-7afc-4934-b661-69961611e228)

**Comment by MitchellBerend** [comment]
Decided this feature doesn't really fit in this project very well.
