### ISSUE TITLE
[Feature Request] Pocketbase (extend with Go) Support

### ISSUE THREAD

**Issue by DaanVervacke** [Melkeydev/go-blueprint#250]
### Tell us about your feature request

Great work with the boilerplate, I was wondering if it would be possible to integrate [Pocketbase (Extend with Go)](https://pocketbase.io/docs/go-overview). As a lot of people use it directly in their Go codebases. It's a quick and easy way to use Pocketbase without settings up a separate instance. This shouldn't be difficult to integrate, the package has a lot of helpers and the documentation is well written.

Thanks in regards!

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
Pocketbase is very interesting, but it is an ecosystem in itself. It eliminates most of the things that Blueprint is trying to do. For now, we don't see how it would integrate and fit into the current codebase.
