### ISSUE TITLE
Go Blueprint Website Command [Bug]

### ISSUE THREAD

**Issue by genortech** [Melkeydev/go-blueprint#256]
### What is the problem?

The command created by the website does not output the correct command for the create my_project part of the command line arguments. It should be create --name my_project.

### Operating System

NA

### Architecture Version (x86, x64, arm, etc)

NA

### Steps to reproduce

Enter Project name 
Copy command line arguments
Enter into terminal
Get prompted to enter name.

**Comment by Ujstor** [comment]
Good catch. It will be fixed.

**Comment by Ujstor** [comment]
fixed
