### ISSUE TITLE
[Bug] API does not start when enable htmx: undefined: HelloPost

### ISSUE THREAD

**Issue by mwolf1989** [Melkeydev/go-blueprint#258]
### What is the problem?

If you bootstrap a new project with

go-blueprint create --name blueprintest --framework standard-library --driver sqlite --advanced true --feature htmx

you can not start the api:

    ~/c/Pr/blueprintest/c/api    main  go run main.go                                             ✔  18:53:30 
# blueprintest/cmd/web
../web/hello.go:15:15: undefined: HelloPost

### Operating System

macOS 14.5

### Architecture Version (x86, x64, arm, etc)

arm

### Steps to reproduce

1. create project with go-blueprint create --name blueprintest --framework standard-library --driver sqlite --advanced true --feature htmx
2. try to start the api 

### Relevant log output

```shell
   ~/c/Pr/blueprintest/c/api    main  go run main.go                                             ✔  18:53:30 
# blueprintest/cmd/web
../web/hello.go:15:15: undefined: HelloPost
```

**Comment by Ujstor** [comment]
You need to follow these steps after a project with HTMX is created:

![image](https://github.com/Melkeydev/go-blueprint/assets/116409846/c0260697-4fad-4e57-b491-01fbc47f68b5)

Install Templ if you don't have it and run templ generate inside the project dir

**Comment by mwolf1989** [comment]
missed this steps. thank you for helping!  Is TailwindCSS already part of the release?

Best Marcel

**Comment by Ujstor** [comment]
Not yet, but soon. The next release will include Tailwind.

I am closing this issue as resolved.
