### ISSUE TITLE
[Feature Request] Support for gofr framework

### ISSUE THREAD

**Issue by kailashchoudhary11** [Melkeydev/go-blueprint#262]
### Tell us about your feature request

I would like to add support for the `gofr` framework.
GoFr is an opinionated microservice development framework.
Here is the link to the github repo https://github.com/gofr-dev/gofr

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
We think that this framework would not fit into the current project structure. It is very opinionated. The goal is to provide an initial project structure as a starting point, not a full solution. Thanks for the suggestion.
