### ISSUE TITLE
[Bug] Installation problem

### ISSUE THREAD

**Issue by alimash76** [Melkeydev/go-blueprint#263]
### What is the problem?

Following installation documentation on the website, I get the following error:

go: github.com/melkeydev/go-blueprint@latest: module github.com/melkeydev/go-blueprint: Get "https://proxy.golang.org/github.com/melkeydev/go-blueprint/@v/list": proxyconnect tcp: EOF

I'm using go version 1.19.4

### Operating System

ubuntu 22.04

### Architecture Version (x86, x64, arm, etc)

linux/amd64

### Steps to reproduce

go install github.com/melkeydev/go-blueprint@latest

### Relevant log output

```shell
go: github.com/melkeydev/go-blueprint@latest: module github.com/melkeydev/go-blueprint: Get "https://proxy.golang.org/github.com/melkeydev/go-blueprint/@v/list": proxyconnect tcp: EOF
```

**Comment by Ujstor** [comment]
I assume this is a network or proxy issue. Try googling how to solve it. You can always clone the source code and run go build and go install. You can also try installing the newest Go version to see if this solves the issue.
