### ISSUE TITLE
[Bug] Go install does not work with new go.mod file

### ISSUE THREAD

**Issue by that-ambuj** [Melkeydev/go-blueprint#287]
### What is the problem?

I was just scaffolding a new project with this awesome tool. but the `go install` command from README.md does not work anymore with the following error:

```bash
❯ go install github.com/melkeydev/go-blueprint@latest
go: github.com/melkeydev/go-blueprint@latest (in github.com/melkeydev/go-blueprint@v0.7.5): go.mod:3: invalid go version '1.22.4': must match format 1.23
```

I'm pretty it's because of mention go patch version in the project's `go.mod` file.

### Operating System

Debian 12

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

Just run the install command from README.md

```bash
go install github.com/melkeydev/go-blueprint@latest
```

### Relevant log output

```shell
go: github.com/melkeydev/go-blueprint@latest (in github.com/melkeydev/go-blueprint@v0.7.5): go.mod:3: invalid go version '1.22.4': must match format 1.23
```

**Comment by that-ambuj** [comment]
I'm using go version 1.19.3, so it might be a change in go.mod file format. I can't pin it down but for now, install version 0.6 works fine for me.

```bash
go install github.com/melkeydev/go-blueprint@v0.6
```

**Comment by Ujstor** [comment]
This isn't a bug per se, you're running an outdated Go version. Please update Go to v1.21 or later. You're running Debian and get old packages when using apt. I'm running Debian myself, but the tools I use for development are always up-to-date. Either build from source or download the latest release from the repository.
