### ISSUE TITLE
[Bug] Unable to create docker-compose.yml file for an SQLite database

### ISSUE THREAD

**Issue by davidhopkins** [Melkeydev/go-blueprint#289]
### What is the problem?

Get an error when creating new project with sqlite. Have tried other DBs and they do not to suffer same issue.

### Operating System

mac 14.5 (23F79)

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

```
❯ go-blueprint create --name dave-test --framework standard-library --driver sqlite --git skip


 ____  _                       _       _
|  _ \| |                     (_)     | |
| |_) | |_   _  ___ _ __  _ __ _ _ __ | |_
|  _ <| | | | |/ _ \ '_ \| '__| | '_ \| __|
| |_) | | |_| |  __/ |_) | |  | | | | | |_
|____/|_|\__,_|\___| .__/|_|  |_|_| |_|\__|
                   | |
                   |_|


 We are unable to create docker-compose.yml file for an SQLite database
            ..
 Next steps:
 • cd into the newly created project with: `cd dave-test`
```

### Relevant log output

```shell
❯ go-blueprint version
Go Blueprint CLI version: v0.7.6
```

**Comment by davidhopkins** [comment]
Ah sqlite just runs inside the same process so i guess there is no need to create the docker compose in the first place!

**Comment by Ujstor** [comment]
Yeah, we need to change the message....it's not clear, the message is ambiguous. SQLite is a file db
