### ISSUE TITLE
[Feature Request] prevent environment variables clash.

### ISSUE THREAD

**Issue by spankie** [Melkeydev/go-blueprint#290]
### Tell us about your feature request

Right now the default environment variables are generic e.g. `DB_HOST`, which can be used by other applications running locally. This can cause clashes by overwriting previous environment variables that already exist. My suggestion is to prefix the default environment variables with the name of the app created. For example, if I create an app with the name `some-app` the environment variables would be prefixed with a sanitized name of the app (`SOME_APP`) like this: `SOME_APP_DB_HOST`

### Disclaimer

- [X] I agree

**Comment by H0llyW00dzZ** [comment]
> ### Tell us about your feature request
> Right now the default environment variables are generic e.g. `DB_HOST`, which can be used by other applications running locally. This can cause clashes by overwriting previous environment variables that already exist. My suggestion is to prefix the default environment variables with the name of the app created. For example, if I create an app with the name `some-app` the environment variables would be prefixed with a sanitized name of the app (`SOME_APP`) like this: `SOME_APP_DB_HOST`
> 
> ### Disclaimer
> * [x]  I agree

Having known this, I think it would be better to use `BLUEPRINT_DB_HOST` or `BP_DB_HOST` as the prefix for the environment variables.

**Comment by spankie** [comment]
Okay, but this would involve the user having to change it again which they can do initially without the `BLUEPRINT_` prefix. And if other projects are created their environment variables will all have the same prefix.

I understand that `godotenv` does not persist the environment variables, but it would be better to have these prefixed with the name of the app.

**Comment by Ujstor** [comment]
We can change the variable name, and the PR will be accepted if someone implements this.
