### ISSUE TITLE
Create a hook to Discord channel for go-blueprint version updates

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#30]
I want a hook to be added to the Discord (https://discord.gg/melkeydevhouse) channel #go-blueprint that will  trigger every time there is a version release.

**Comment by mikelerch** [comment]
There's a lot of different [GitHub Actions](https://github.com/marketplace?category=&type=actions&verification=&query=discord) that you can use.

**Comment by HarshPatel5940** [comment]
Just use discord webhook's and pass that into settings repo event settings. That would be simpler and better to work with.
