### ISSUE TITLE
[Feature Request] Remove `Internal` Directory

### ISSUE THREAD

**Issue by utamori** [Melkeydev/go-blueprint#300]
### Tell us about your feature request

imho, The code generated by this tool is a server, not a library, 
so `internal` direcotry is not necessary.
what do you think?

### Disclaimer

- [X] I agree

**Comment by Dogers** [comment]
But isn't anything outside the `internal` directory a package that can be called/used as a library by any other application? Having it in there prevents others from using it..?

**Comment by ccoVeille** [comment]
that's the purpose of `internal`, I think it's the good approaches

@utamori unless you have plan to call the code as a library, there is no logic of exposing internal

The purpose of internal is to avoid issues and facilitate refactoring

if something is in internal, it can be refactored totally and even removed.

**Comment by Ujstor** [comment]
I agree, there is no good reason why the internal directory should be removed, nor should the directory structure in general be changed.
