### ISSUE TITLE
gRPC Implementation

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#31]
It would be super interesting to see if we can include a gRPC implementation.
If someone does this, I want to use Twirp package.

**Comment by ljpurcell** [comment]
@Melkeydev love the project. I haven't ever touched gRPC before but have been meaning to get some experience with it. I'm happy to take a crack at this if no one else has plans. Thanks!

**Comment by Melkeydev** [comment]
@ljpurcell Yeah no problem, please take it over. However, I do want to say can we integrate Twirp? It is a RPC client.
https://github.com/twitchtv/twirp

**Comment by ljpurcell** [comment]
@Melkeydev yep totally. Sorry, saw that in your original description and fully on board with that 👍
