### ISSUE TITLE
[Feature Request] Implementing ScyllaDB as a Provider

### ISSUE THREAD

**Issue by DanielHe4rt** [Melkeydev/go-blueprint#319]
### Tell us about your feature request

Hey! I just found the project and it looks just amazing, so congratz for the initiative.

I want to contribute by adding a new DB Layer with ScyllaDB (CQL) using the [GoCQL Driver](https://github.com/scylladb/gocql). There's any development flow that I should follow or I can just send the Pull Request? I can maintain it in the long term without problems.

### Disclaimer

- [X] I agree

**Comment by DanielHe4rt** [comment]
I had some free time today so made the implementation with all needed tests. 

Let me know if something is missing, please.

closes #320

**Comment by Ujstor** [comment]
@DanielHe4rt 
Thanks for the PR, and sorry for the delay. We will check it and let you know if everything works as expected. Personally, I don't have experience with Scylla, but your long-term commitment to maintaining it sounds really good.

**Comment by Ujstor** [comment]
Merged
