### ISSUE TITLE
Squash and merge all commits 

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#32]
Can we squash all the previous commits on the main branch?

**Comment by itschip** [comment]
Likely you/codeowner that has to do an interactive rebase and force push it. Doing this through a PR is ugh.

**Comment by mimatache** [comment]
You can also enforce this type of merge in the GitHub settings page, and only leave the `Squash and Merge` Option:
![image](https://github.com/Melkeydev/go-blueprint/assets/25421522/eccf1f57-7227-4bab-b5d3-810e3ef58167)

Here, you can enforce what type of merges you would like to allow.
