### ISSUE TITLE
[Feature Request] Add output.css to .gitignore if Tailwind is used

### ISSUE THREAD

**Issue by LarsArtmann** [Melkeydev/go-blueprint#323]
### Tell us about your feature request

Add code below to .gitignore if Tailwind is used.
```.gitignore
# Tailwind CSS
cmd/web/assets/css/output.css
```

### Disclaimer

- [X] I agree

**Comment by LarsArtmann** [comment]
We may should also consider not removing `cmd/template/advanced/files/tailwind/output.css.tmpl` if possible

**Comment by LarsArtmann** [comment]
We also seem to generate a `./tailwindcss` file. It should also be excluded.

**Comment by Ujstor** [comment]
Merged, thanks for the PR.
