### ISSUE TITLE
[Bug] make tailwind should be called tailwind-install instead

### ISSUE THREAD

**Issue by LarsArtmann** [Melkeydev/go-blueprint#326]
### What is the problem?

`make tailwind` feels like it is there to create an `output.css` file.
But it only installs tailwind if you do not already have it.
As with `make templ-install`, we should be consistent with the naming.

### Operating System

ALL

### Architecture Version (x86, x64, arm, etc)

ALL

### Steps to reproduce

run `make tailwind`

### Relevant log output

```shell
None
```

**Comment by pradytpk** [comment]
I would to Like to work on this issue.
Can you please assign me.

**Comment by Ujstor** [comment]
This is yours. I will check the PR

**Comment by Ujstor** [comment]
Merged, tnx.
