### ISSUE TITLE
[Bug] /assets/css/input.css is publicly accessible

### ISSUE THREAD

**Issue by LarsArtmann** [Melkeydev/go-blueprint#328]
### What is the problem?

Should the /assets/css/input.css file be publicly accessable?

### Operating System

ALL

### Architecture Version (x86, x64, arm, etc)

ALL

### Steps to reproduce

```shell
make build
make run
```
Vistit [http://localhost:8080/assets/css/input.css](http://localhost:8080/assets/css/input.css)

### Relevant log output

```shell
N/A
```

**Comment by Ujstor** [comment]
Good suggestion, we will accept the PR.
