### ISSUE TITLE
the installation on the go latest version no working

### ISSUE THREAD

**Issue by NPKIN78** [Melkeydev/go-blueprint#336]
### What is the problem?

 ~/workspace/goprojects  go install github.com/melkeydev/go-blueprint@latest
go: github.com/melkeydev/go-blueprint@latest (in github.com/melkeydev/go-blueprint@v0.10.0): go.mod:3: invalid go version '1.22.4': must match format 1.23

### Operating System

debian 12

### Architecture Version (x86, x64, arm, etc)

amd64

### Steps to reproduce

i have installed go from the official documentation then wen installing the go-blueprint i encounter the issue

**Comment by yusuke0627** [comment]
Should upgrade go version to 1.23?(mod.go)

https://github.com/Melkeydev/go-blueprint/blob/ff91dcef95bf4dd043d1ac2a86603c8d87a4559b/go.mod#L3 #
