### ISSUE TITLE
[Bug] Frontend app is expecting the Go app to be running in localhost:8080 

### ISSUE THREAD

**Issue by mdelapenya** [Melkeydev/go-blueprint#350]
### What is the problem?

This works pretty well unless the PORT env var is changed, i.e. to 8081. Then, the frontapp is disconnected from the backend because it's hardcoding the URL where it lives.

As a consequence, the frontend app communicates to the service using localhost:8080, instead of using the service name declared in the compose file, `app`, and the port using the PORT env var.

I think the Go app should not be exposed in the port, but instead being accessed by the frontend, only (this is an opinion, and could be discussed in a separate issue.

### Operating System

Docker

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

1. Generate an app using the Dockerised approach:
```shell
go run . create create --name pokemon-battle --framework fiber --driver postgres --advanced --feature react --feature docker --feature githubaction --git commit
```

2. change the PORT in .env

```env
PORT=8081
# rest of variables
```

3. start the app:
```shell
docker compose up --build
```

4. browse the app and click the `Click to fetch from Go server` button.

### Relevant log output

Chrome console tab:
```shell
Failed to load resource: net::ERR_CONNECTION_REFUSED
index-CLyHzpwY.js:40 Error fetching data: TypeError: Failed to fetch
    at m (index-CLyHzpwY.js:40:57777)
    at Object.ja (index-CLyHzpwY.js:37:9826)
    at Fa (index-CLyHzpwY.js:37:9980)
    at Ua (index-CLyHzpwY.js:37:10037)
    at Vi (index-CLyHzpwY.js:37:31376)
    at Ai (index-CLyHzpwY.js:37:31793)
    at index-CLyHzpwY.js:37:36715
    at po (index-CLyHzpwY.js:40:36823)
    at Ko (index-CLyHzpwY.js:37:8962)
    at du (index-CLyHzpwY.js:37:33079)
(anonymous) @ index-CLyHzpwY.js:40
```

Chrome network tab:
```
Request URL:
http://localhost:8080/
Referrer Policy:
strict-origin-when-cross-origin
```

**Comment by Ujstor** [comment]
We hardcoded the backend port 8080 in React. We need to use an env variable instead. Thanks for the heads-up. 

This is a good first issue. If someone wants to work on it, it is available as long as no one is assigned to it.

**Comment by sibteali786** [comment]
hey @Ujstor  i can try to work on it as i am learning GO so it can be a good learning experience for me as well

**Comment by sibteali786** [comment]
Also the solution is rather not simple, as we need to consume PORT as env variable which is strictly named as `VITE_..` in vite based environments so 
1. if i modify the globalTempate specifically for react scenario causes conflicts with dockerFile and docker-compose.yaml when building the container. 

I am looking into some solutions, but pretty sure that would need to modify the docker File and docker-compose templates or globalEnv template.

would appreciate any suggestion here.

**Comment by Ujstor** [comment]
Nice, I'll assign the issue to you.

**Comment by Ujstor** [comment]
Merged.
