### ISSUE TITLE
[Feature Request] No-server blueprint

### ISSUE THREAD

**Issue by ksandvik** [Melkeydev/go-blueprint#359]
### Tell us about your feature request

Any chance to just start a file system as a no-server setup, for tools and such? It could even be a specific flag that bypasses all the other options, such as -vanilla? 

### Disclaimer

- [X] I agree

**Comment by Ujstor** [comment]
Can you explain a little more why you would like to see this option and what purpose it will have? Which cases will it cover?

**Comment by ksandvik** [comment]
For quickly writing various cli tools. I could make a similar scripted system but would be nice to incorporate it all into a single template tool.

**Comment by Ujstor** [comment]
I am afraid that this is out of the project scope :)

**Comment by ksandvik** [comment]
OK, should be pretty simple so I will steal the Makefile and the file structure and make my own then.

**Comment by Ujstor** [comment]
Send me repo link once you have the config.
