### ISSUE TITLE
Proposal: Move template strings to separate files.

### ISSUE THREAD

**Issue by mimatache** [Melkeydev/go-blueprint#49]
This is a proposal to move the template strings from the template directory to separate files outside of the execution code, especially for the full files.

We can use the [go embed](https://pkg.go.dev/embed) functionality to ship them with the binaries and make the templates be easier to view, manage and format independently of the execution code. 

For naming proposal we could have the files be named with the generated file name and with a `.tmpl` extension at the end, something like `main.go.tmpl`.

As the project grows and adds new files and functionality it will become increasingly difficult to manage the template strings directly as multi line strings in the go files.

Example:

![image](https://github.com/Melkeydev/go-blueprint/assets/25421522/ec8bc482-d475-40d7-97dd-abdc59469d66)
> Directory proposal

```go
package main

import (
	"{{.ProjectName}}/internal/server"
)

func main() {

	server := server.NewServer()

	err := server.ListenAndServe()
	if err != nil {
		panic("cannot start server")
	}
}
```
> `main.go.tmpl` contents 

```go
// Package template provides utility functions that
// help with the templating of created files.
package template

import (
  _"embed"
)


//go:embed resources/main/main.go.tmpl
var mainTemplate []byte

// MakeHTTPRoutes returns a byte slice that represents 
// the default cmd/api/main.go file template.
func MainTemplate() []byte {
	return mainTemplate
}
```
> Changes in the `main.go` file in templates.

This will be doubly helpful for the `README.md` and  '.air.toml` files, as they will simply be the files.

We could also use the `resources` (or whatever else we decide to call it) as a mirror of what we want the final project to look like and use the `embed.FS` to walk the files.

**Comment by Melkeydev** [comment]
This is a pretty interesting idea - i might not fully know how it works. 
So each file is defined as a regular .go file (or whatever)and is brought in?

**Comment by mimatache** [comment]
Something like that (again .tmpl and whatever since the language server will go bonkers with the templating specifics), and the go compiler brings them into the binary and build time. 
For me, I always found it annoying to try to keep good formatting in strings.

I you find this interesting, I can try to create a PR (though I have a pretty family intensive weekend ahead).
