### ISSUE TITLE
Abort if project directory already exists

### ISSUE THREAD

**Issue by Frosthage** [Melkeydev/go-blueprint#54]
## Description

The application currently creates a new project directory and files based on the provided project name, even if a directory with the same name already exists. This behavior is problematic as it could lead to unintended overwriting of existing project data. The application should instead abort creation when a project with the same name already exists.

## Steps to Reproduce

Run `go-blueprint create` in a directory with a sub directory called the same as the name of the project. 

## Expected Result

When attempting to create a project with a name matching an existing project, the application should provide an error message and abort the creation process to avoid overwriting the existing project.

**Comment by Frosthage** [comment]
I can do it if it up for grabs.

**Comment by Melkeydev** [comment]
@Frosthage All you- would love to see what you come up with

**Comment by nickwarters** [comment]
Hey @Melkeydev / @Frosthage I think this seems to have already been implemented here unless I'm not quite understanding the issue.  [program/program.go#110](https://github.com/Melkeydev/go-blueprint/blob/0b2cfb2321adeda35fc97809dcc0ccb1ab03699c/cmd/program/program.go#L110)

Also when I ran the command twice with the same project name I got an error as the project already exists (as expected).

**Comment by basokant** [comment]
I think the panic error right now says

```
2023/11/11 05:13:44 Could not initialize go.mod in new project exit status 1
Error: exit status 1
```

Ideally this would be more descriptive of the problem.

**Comment by nickwarters** [comment]
I meant the requested functionality exists but yes the error message could me more descriptive

**Comment by Melkeydev** [comment]
yep - I think youre both right.
If we can improve the error handling on these - that would be great. @basokant if you want to take a crack at it

**Comment by Frosthage** [comment]
> Hey @Melkeydev / @Frosthage I think this seems to have already been implemented here unless I'm not quite understanding the issue. [program/program.go#110](https://github.com/Melkeydev/go-blueprint/blob/0b2cfb2321adeda35fc97809dcc0ccb1ab03699c/cmd/program/program.go#L110)
> 
> Also when I ran the command twice with the same project name I got an error as the project already exists (as expected).

That block only creates the directory if it does not exist. In my opinion, we should put an else block returning error.

> I think the error right now says
> 
> ```
> 2023/11/11 05:13:44 Could not initialize go.mod in new project exit status 1
> Error: exit status 1
> ```
> 
> Ideally this would be more descriptive of the problem.

This only happens if a file such as go.mod already exists. I accidentally created a project where I've previously created a nodejs project and it worked just fine.

**Comment by nickwarters** [comment]
Gotcha @Frosthage! 
I just added a PR for this.
