### ISSUE TITLE
Proposal: Add ability to save a template of the command

### ISSUE THREAD

**Issue by nickwarters** [Melkeydev/go-blueprint#57]
Getting a bit meta with a template of a template, but as this project grows and new options get added like #11 it could be good to add ability to save a template of the project using the options selected. 

Currently it's only name and framework but I saw there is an open issue (#11) for adding db setup too. If the db setup issue gets added then having a re-usable thing with only the name needing to be suppled would be useful. 

example usage could be something like:
`go-blueprint create --name test-project --framework gin --save-template new-template` or selected at the end if using the interactive version. 
Then something like this to use the template
`go-blueprint create --template new-template --name not-another-test-project`

**Comment by basokant** [comment]
What would be the difference between this and say, making the "template" just be a shell alias or native completion?

**Comment by nickwarters** [comment]
No difference really other than it be built in

**Comment by Melkeydev** [comment]
This is a really cool idea but I do have a concern on how this could scale. 
Or, better yet, how do we save all the combinations possible to then be re-used? Where would these combo's be saved and referenced?

**Comment by nickwarters** [comment]
I dont think you need to save all the possible combinations, just allow the user to save one they are currently running. 
In terms of where to save, ~/.config/go-blueprint/some-config-file ???
