### ISSUE TITLE
Proposal: Add optional default root directory

### ISSUE THREAD

**Issue by nickwarters** [Melkeydev/go-blueprint#58]
If you have all of your projects in a specific directory, rather than needing to run the command in that directory, it could be useful to be able to run the command from anywhere and the project be created in your base/root project directory.

For example I could be in `~/some/random/path` and by running `go-blueprint create --name new-project` would create the project in `~/dev/new-project`

**Comment by basokant** [comment]
Not sure about the default root directory, but I do agree that only being able to choose the name is a bit limiting. It could be nice to instead have the step be called "path" which would allow you to pass in an absolute/relative path to the directory that the project should live. if the directory doesn't exist, it would be nice if it created it (same with any of it's parent directories).

@nickwarters Would this give the same utility? I've seen other bootstrap CLI tools do this too. (ex. `npm create astro@latest`)

**Comment by nickwarters** [comment]
I think a path option would be good yea. 

My original idea was kinda have it optional rather than default. 
Be able to set it in a global config or something.

**Comment by nickwarters** [comment]
@basokant were you going to take a crack at this? If not I'd like to :)
