### ISSUE TITLE
cd into the newly create project once created

### ISSUE THREAD

**Issue by nickwarters** [Melkeydev/go-blueprint#60]
I could be wrong on this one but I would think the default next action for someone after creating a new project would be to cd into it. It could improve the user experience to do this for them. 

For those times when the user doesn't need to cd into the project straight away a new flag could be added to stop the changing of the directory.

For example: `go-blueprint create --name new-project --no-cd` or something more fitting.

**Comment by basokant** [comment]
Honestly I've never used a bootstrap CLI (ex. `npx create-next-app`, `npm create astro@latest`, `npx create-react-app`) that has had this behaviour. Not sure about the benefits to the user experience since it's literally just one line to cding into it. I agree though somewhat it could be nice! @nickwarters what do you think?

**Comment by nickwarters** [comment]
No I think you definitely have a point about no other tools doing it. 

It's just always bugged me with every tool I'm in the mindset of starting a project, I've created the project, of course I want to be in the project.

**Comment by Melkeydev** [comment]
This is a good idea - not against it at all!

**Comment by itschip** [comment]
If added, I think it should be an opt-in at least, not opt-out.

**Comment by nickwarters** [comment]
Yea reflecting on it, it's one of my pet peeves to deal with... going with the majority (literally every other 'create project' tool) is probably the way to go!

**Comment by newtoallofthis123** [comment]
Um...just a small doubt, is it really possible for the go program to modify the current working directory of it's parent process? I don't think I have ever come across a case like that

**Comment by nickwarters** [comment]
Yea let's close
