### ISSUE TITLE
Proposal: shell completion for `--framework` flag

### ISSUE THREAD

**Issue by MitchellBerend** [Melkeydev/go-blueprint#61]
It would be nice if the `completion` command would also generate completion for the `--framework` flag. It will help with feature discovery for new users.

**Comment by basokant** [comment]
Every Cobra CLI app has access to the

```
go-blueprint completion [bash/zsh/fish]
```

command, which generates shell completions.

HOWEVER, a bit of setup is required for permitted flag values in Cobra, which would be required to get autocomplete working for the `--framework` flag. See https://stackoverflow.com/questions/50824554/permitted-flag-values-for-cobra/70541824#70541824

1. Make a new type that implements the `pflag.Value` interface, that is also a string enum (ie. `frameworkEnum`), which enumerates the possible frameworks that we support.
2. Use enum in the registration of the `create` command. See `init()` function.

```
cmd.Flags().Var(&frameworkEnum, "framework", `framework. allowed: "chi", "standard library", "gin", etc...`)
```

**Comment by basokant** [comment]
I might take this guy, will start working on it later tho so if anyone wants to work on it go ahead (check out the comment above for some tips from yours truly 😄)
