### ISSUE TITLE
Proposal: Add ability to use own templates

### ISSUE THREAD

**Issue by nickwarters** [Melkeydev/go-blueprint#62]
Could be useful to be able to use own templates for projects or files.

**Comment by basokant** [comment]
This would be interesting! I guess an initial consideration is that it would take away from how opinionated the blueprints are. At the end of the day as long as the default blueprint(s) are good this could be useful. 

Honestly though if someone wanted to create their own template of sorts, I feel like it would be easier to just have a template repo that THEY can fork and clone down instead, which would give them more control of the template out of the box. I might be missing the appeal but let me know your thoughts @nickwarters.

**Comment by nickwarters** [comment]
I think the default templates are great and probably what I would use 90% of the time. I guess my idea was more around 1-2 additional templates or files a user might want to add for themselves rather than replacing everything in the defaults. 

For those who find the default isn't quite enough or always find themselves creating specific routes, they could override the default just for them. 

For example supplying your own routes template to create '/', 'status', and 'about' routes rather than just the default hello world one.

**Comment by nickwarters** [comment]
> I guess an initial consideration is that it would take away from how opinionated the blueprints are.

Just to confirm from my perspective on this point, I like how opinionated the defaults are, I think it's good to start opinionated. Just as you use a tool more and make more projects you start to get into your own rhythms and just need to change a few things to keep up with your needs.
