### ISSUE TITLE
Proposal: Add docker-compose files to spin up local DB's 

### ISSUE THREAD

**Issue by Melkeydev** [Melkeydev/go-blueprint#65]
As we are adding DB opt-in support I thought (in this convo https://github.com/Melkeydev/go-blueprint/pull/22#pullrequestreview-1723537953) that we can add a docker-compose file that can easily spin up a DB.
Users will literally have a working DB OOB

**Comment by muandane** [comment]
@Melkeydev what type of dbs ?

**Comment by joshjms** [comment]
Maybe can choose (add another option to choose from in the cli)?

**Comment by cayo-rodrigues** [comment]
@Melkeydev We could add Dockerfile and docker-compose for the go server as well. Maybe one dockerfile for development (using air) and another for production making it as small as possible.

**Comment by Melkeydev** [comment]
![image](https://github.com/Melkeydev/go-blueprint/assets/53410236/8a5cacc6-d282-4c54-834c-ef55608ed01c)

This is what I think is the best solution.
Here I have a docker-compose file that is spinning up a Postgres DB.

Then we bind it to the .env variables and ta-da!
